const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const PORT = Number(process.env.PORT || 10000);
const APP_ID = String(process.env.DERIV_APP_ID || '').trim();
const BASE_URL = String(process.env.NEXT_PUBLIC_BASE_URL || 'https://izidro.onrender.com').trim().replace(/\/$/, '');
const REDIRECT_URI = String(process.env.REDIRECT_URL || `${BASE_URL}/api/auth/callback`).trim();
const AUTHORIZE_URL = 'https://auth.deriv.com/oauth2/auth';
const TOKEN_URL = 'https://auth.deriv.com/oauth2/token';
const DERIV_API_URL = 'https://api.derivws.com';
const SESSION_TTL = 7 * 24 * 60 * 60 * 1000;
const OAUTH_TTL = 10 * 60 * 1000;
const oauthStates = new Map();
const sessions = new Map();

function configError(){const missing=[];if(!APP_ID)missing.push('DERIV_APP_ID');if(!BASE_URL)missing.push('NEXT_PUBLIC_BASE_URL');if(!REDIRECT_URI)missing.push('REDIRECT_URL');return missing}
function randomToken(bytes=32){return crypto.randomBytes(bytes).toString('base64url')}
function sha256(value){return crypto.createHash('sha256').update(value).digest('base64url')}
function parseCookies(header=''){const out={};for(const part of header.split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function cookie(name,value,options={}){const parts=[`${name}=${encodeURIComponent(value)}`,`Path=${options.path||'/'}`];if(options.httpOnly!==false)parts.push('HttpOnly');parts.push(`SameSite=${options.sameSite||'Lax'}`);if(options.maxAge!=null)parts.push(`Max-Age=${options.maxAge}`);if(options.secure!==false)parts.push('Secure');return parts.join('; ')}
function clearCookie(name){return cookie(name,'',{maxAge:0})}
function json(res,status,body,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(body))}
function redirect(res,location,headers={}){res.writeHead(302,{Location:location,'Cache-Control':'no-store',...headers});res.end()}
async function exchangeCode(code,verifier){const body=new URLSearchParams({grant_type:'authorization_code',client_id:APP_ID,code,redirect_uri:REDIRECT_URI,code_verifier:verifier});const response=await fetch(TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json().catch(()=>null);if(!response.ok||!data?.access_token)throw new Error(`OAuth token exchange failed (${response.status}): ${data?.error_description||data?.error||'unknown error'}`);return data}
function sessionFromRequest(req){const id=parseCookies(req.headers.cookie||'')['__Host-izitrader_session'];if(!id)return null;const session=sessions.get(id);if(!session)return null;if(session.expiresAt<Date.now()){sessions.delete(id);return null}return{id,...session}}
async function derivRequest(session,pathname,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${session.accessToken}`,'Deriv-App-ID':APP_ID};let response=await fetch(`${DERIV_API_URL}${pathname}`,{...options,headers});let data=await response.json().catch(()=>null);if((response.status===401||response.status===403)&&session.refreshToken){try{const body=new URLSearchParams({grant_type:'refresh_token',client_id:APP_ID,refresh_token:session.refreshToken});const rr=await fetch(TOKEN_URL,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const rt=await rr.json().catch(()=>null);if(rr.ok&&rt?.access_token){session.accessToken=rt.access_token;session.refreshToken=rt.refresh_token||session.refreshToken;session.tokenExpiresAt=Date.now()+Number(rt.expires_in||3600)*1000;headers.Authorization=`Bearer ${session.accessToken}`;response=await fetch(`${DERIV_API_URL}${pathname}`,{...options,headers});data=await response.json().catch(()=>null)}}catch{}}if(!response.ok)throw Object.assign(new Error(data?.errors?.[0]?.message||`Deriv API error (${response.status})`),{status:response.status,data});return data}
function extractAccounts(payload){const data=payload?.data;if(Array.isArray(data))return data;if(data&&typeof data==='object'){if(Array.isArray(data.accounts))return data.accounts;if(data.account_id)return[data]}return[]}
function contentType(file){const ext=path.extname(file).toLowerCase();return({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.ico':'image/x-icon'})[ext]||'application/octet-stream'}
function serveStatic(req,res){const pathname=decodeURIComponent(new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname);const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/,'');const file=path.resolve(__dirname,relative);if(!file.startsWith(path.resolve(__dirname)+path.sep))return json(res,403,{error:'Forbidden'});fs.readFile(file,(err,data)=>{if(err)return json(res,404,{error:'Not found'});if(pathname==='/'){let html=data.toString('utf8');html=html.replace('href="https://track.deriv.com/_PZZnG4RWbBdZl7VyVw174GNd7ZgqdRLk/1/" target="_blank" rel="noopener" id="loginLink"','href="/api/auth/login" id="loginLink"');html=html.replace(/\s*<button[^>]*id="demoAccess"[^>]*>[\s\S]*?<\/button>/i,'');html=html.replace(/\s*<div[^>]*class="auth-note"[^>]*>[\s\S]*?<\/div>/i,'');html=html.replace(/\s*<title>[^<]*<\/title>/i,'<title>Izitrader</title>');if(!html.includes('/auth.js'))html=html.replace('</body>','<script src="/auth.js"></script></body>');if(!html.includes('/react-deriv-bot.js'))html=html.replace('</body>','<script src="/react-deriv-bot.js"></script></body>');data=Buffer.from(html,'utf8')}res.writeHead(200,{'Content-Type':contentType(file),'Cache-Control':pathname==='/'?'no-cache':'public, max-age=300'});res.end(data)})}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);const missing=configError();
if(url.pathname==='/api/auth/login'&&req.method==='GET'){if(missing.length)return json(res,500,{error:'OAuth server configuration is incomplete',missing});const verifier=randomToken(32),challenge=sha256(verifier),state=randomToken(24);oauthStates.set(state,{createdAt:Date.now()});const auth=new URL(AUTHORIZE_URL);auth.searchParams.set('response_type','code');auth.searchParams.set('client_id',APP_ID);auth.searchParams.set('redirect_uri',REDIRECT_URI);auth.searchParams.set('scope','trade');auth.searchParams.set('state',state);auth.searchParams.set('code_challenge',challenge);auth.searchParams.set('code_challenge_method','S256');return redirect(res,auth.toString(),{'Set-Cookie':[cookie('__Host-izitrader_oauth_state',state,{maxAge:OAUTH_TTL/1000}),cookie('__Host-izitrader_oauth_verifier',verifier,{maxAge:OAUTH_TTL/1000})]})}
if(url.pathname==='/api/auth/callback'&&req.method==='GET'){const cookies=parseCookies(req.headers.cookie||''),code=url.searchParams.get('code'),state=url.searchParams.get('state'),oauthError=url.searchParams.get('error');if(oauthError)return redirect(res,`/?auth_error=${encodeURIComponent(oauthError)}`,{'Set-Cookie':[clearCookie('__Host-izitrader_oauth_state'),clearCookie('__Host-izitrader_oauth_verifier')]});const cookieState=cookies['__Host-izitrader_oauth_state'],verifier=cookies['__Host-izitrader_oauth_verifier'],pending=state&&oauthStates.get(state);if(!code||!state||!verifier||state!==cookieState||!pending||Date.now()-pending.createdAt>OAUTH_TTL)return redirect(res,'/?auth_error=invalid_oauth_state',{'Set-Cookie':[clearCookie('__Host-izitrader_oauth_state'),clearCookie('__Host-izitrader_oauth_verifier')]});oauthStates.delete(state);try{const token=await exchangeCode(code,verifier),sessionId=randomToken(32);sessions.set(sessionId,{accessToken:token.access_token,refreshToken:token.refresh_token||null,tokenExpiresAt:Date.now()+Number(token.expires_in||3600)*1000,createdAt:Date.now(),expiresAt:Date.now()+SESSION_TTL});return redirect(res,'/',{'Set-Cookie':[cookie('__Host-izitrader_session',sessionId,{maxAge:SESSION_TTL/1000}),clearCookie('__Host-izitrader_oauth_state'),clearCookie('__Host-izitrader_oauth_verifier')]})}catch(error){console.error('[Izitrader OAuth callback]',error.message);return redirect(res,'/?auth_error=token_exchange_failed',{'Set-Cookie':[clearCookie('__Host-izitrader_oauth_state'),clearCookie('__Host-izitrader_oauth_verifier')]})}}
if(url.pathname==='/api/auth/session'&&req.method==='GET'){const session=sessionFromRequest(req);return json(res,200,session?{authenticated:true,expiresAt:session.expiresAt,tokenExpiresAt:session.tokenExpiresAt}:{authenticated:false})}
if(url.pathname==='/api/deriv/accounts'&&req.method==='GET'){const session=sessionFromRequest(req);if(!session)return json(res,401,{error:'Not authenticated'});try{const payload=await derivRequest(session,'/trading/v1/options/accounts');const accounts=extractAccounts(payload);return json(res,200,{data:accounts,accounts,raw:payload})}catch(error){return json(res,error.status||502,{error:error.message,details:error.data?.errors||null})}}
if(url.pathname==='/api/deriv/ws-url'&&(req.method==='GET'||req.method==='POST')){const session=sessionFromRequest(req);if(!session)return json(res,401,{error:'Not authenticated'});let accountId='';if(req.method==='GET')accountId=String(url.searchParams.get('account_id')||'').trim();else{let body='';for await(const chunk of req)body+=chunk;let payload={};try{payload=body?JSON.parse(body):{}}catch{return json(res,400,{error:'Invalid JSON'})}accountId=String(payload.account_id||'').trim()}if(!/^[A-Z]{2,8}\d{5,}$/.test(accountId))return json(res,400,{error:'Invalid account_id'});try{const result=await derivRequest(session,`/trading/v1/options/accounts/${encodeURIComponent(accountId)}/otp`,{method:'POST'});const wsUrl=result?.data?.url;if(!wsUrl)return json(res,502,{error:'Deriv did not return an authenticated WebSocket URL'});return json(res,200,{data:{url:wsUrl},wsUrl,account_id:accountId})}catch(error){return json(res,error.status||502,{error:error.message,details:error.data?.errors||null})}}
if(url.pathname==='/api/auth/logout'&&(req.method==='GET'||req.method==='POST')){const session=sessionFromRequest(req);if(session)sessions.delete(session.id);return json(res,200,{ok:true},{'Set-Cookie':clearCookie('__Host-izitrader_session')})}
if(url.pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,oauth:true,derivApi:true,configured:missing.length===0,missing});return serveStatic(req,res)}catch(error){console.error('[Izitrader OAuth]',error);return json(res,500,{error:'Internal server error'})}});
setInterval(()=>{const now=Date.now();for(const[state,item]of oauthStates)if(now-item.createdAt>OAUTH_TTL)oauthStates.delete(state);for(const[id,session]of sessions)if(session.expiresAt<now)sessions.delete(id)},60000).unref();
server.listen(PORT,'0.0.0.0',()=>console.log(`[Izitrader] listening on ${PORT}; OAuth redirect: ${REDIRECT_URI||'(not configured)'}`));