'use client';

import { FormEvent, useEffect, useState } from 'react';

type User={id:string|number;name:string;email:string};

type AuthState={user:User|null;derivConnected:boolean;loading:boolean};

const RiskWarning=()=> <div style={{marginTop:18,padding:'14px 15px',border:'1px solid #f0b8bc',borderRadius:12,background:'#fff7f8',textAlign:'left'}}><div style={{fontSize:12,fontWeight:900,letterSpacing:'.06em',color:'#e30613',marginBottom:7}}>⚠ AVISO DE RISCO</div><div style={{fontSize:11,lineHeight:1.5,color:'#333'}}>Negociar opções digitais envolve um elevado nível de risco. Pode perder todo o valor investido numa operação. Nunca negocie dinheiro que não possa perder e certifique-se de que compreende os riscos antes de operar.</div><div style={{fontSize:10,lineHeight:1.45,color:'#777',marginTop:7}}>O Izitrader é uma ferramenta de negociação e não constitui aconselhamento financeiro nem garante lucros.</div><a href="https://deriv.com/risk-disclosure" target="_blank" rel="noopener noreferrer" style={{display:'inline-block',marginTop:8,fontSize:10,color:'#e30613',fontWeight:800,textDecoration:'none'}}>Ler divulgação de risco da Deriv</a></div>;

export default function Home(){
 const [auth,setAuth]=useState<AuthState>({user:null,derivConnected:false,loading:true});
 const [mode,setMode]=useState<'login'|'register'>('register');
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');
 const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/auth/me',{cache:'no-store'});if(r.ok){const d=await r.json();setAuth({user:d.user,derivConnected:!!d.derivConnected,loading:false})}else setAuth({user:null,derivConnected:false,loading:false})}catch{setAuth({user:null,derivConnected:false,loading:false})}}
 useEffect(()=>{load();const p=new URLSearchParams(location.search);if(p.get('deriv_connected'))setMessage('Conta Deriv conectada com sucesso.');if(p.get('auth_error'))setError(p.get('auth_error')||'Erro de autenticação.')},[]);
 useEffect(()=>{if(auth.user&&auth.derivConnected){window.location.replace('/dashboard.html')}},[auth.user,auth.derivConnected]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');const endpoint=mode==='register'?'/api/auth/register':'/api/auth/platform-login';const body=mode==='register'?{name,email,password,confirmPassword:confirm}:{email,password};try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível continuar.');setAuth({user:d.user,derivConnected:!!d.derivConnected,loading:false});if(mode==='register')setMessage('Conta Izitrader criada. Agora conecte a sua conta Deriv.')}catch(e){setError(e instanceof Error?e.message:'Erro inesperado.')}finally{setBusy(false)}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});setAuth({user:null,derivConnected:false,loading:false});setMode('login')}
 if(auth.loading)return <main className="page"><div className="shell"><Brand/><div className="card muted">A carregar a sua conta...</div></div></main>;
 if(auth.user&&!auth.derivConnected)return <main className="page"><div className="shell"><div className="top"><Brand/><div className="user"><strong>{auth.user.name}</strong><small>{auth.user.email}</small></div></div><div className="card"><h1 className="title">Conta Izitrader</h1><p className="muted">A conta foi criada. O próximo passo é conectar a sua conta da Deriv.</p><div className="connect card"><h2>Conectar Deriv</h2><p className="muted">Será redirecionado para a página oficial da Deriv para iniciar sessão e autorizar o Izitrader.</p><a className="btn primary" style={{display:'block',textAlign:'center',textDecoration:'none'}} href="/api/auth/login">Continuar com Deriv</a></div>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<button className="btn secondary" onClick={logout}>Sair</button><RiskWarning/></div></div></main>;
 return <main className="page"><div className="shell"><Brand/><div className="card"><div className="tabs"><button className={`tab ${mode==='register'?'active':''}`} onClick={()=>{setMode('register');setError('')}}>Criar conta</button><button className={`tab ${mode==='login'?'active':''}`} onClick={()=>{setMode('login');setError('')}}>Entrar</button></div><h1 className="title">{mode==='register'?'Criar conta Izitrader':'Entrar no Izitrader'}</h1><p className="muted">{mode==='register'?'Crie a sua conta da plataforma e depois conecte a Deriv.':'Entre na sua conta Izitrader para continuar.'}</p><form onSubmit={submit}>{mode==='register'&&<><label className="label">NOME</label><input className="input" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/></>}<label className="label">EMAIL</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><label className="label">PASSWORD</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='register'?'new-password':'current-password'} required/>{mode==='register'&&<><label className="label">CONFIRMAR PASSWORD</label><input className="input" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></>}<button className="btn primary" disabled={busy}>{busy?'Aguarde...':mode==='register'?'Criar conta':'Entrar'}</button></form>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<div className="foot">A password fica no servidor; não é enviada para a Deriv.</div><RiskWarning/></div></div></main>;
}
function Brand(){return <div className="brand"><div className="logo">I</div><div className="brandName">Izi<span>trader</span></div></div>}
